server:
  port: 9091

logging:
  level:
    org:
      springframework: INFO 


spring:
  application:
    name: Credit_History_Check

  profiles:
    active: prod          

#Eureka Client Configuration

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-server: true
    service-url:
      defaultZone: http://localhost:8761/eureka  