# server:
#   port: 8080

logging:
  level:
    org:
      springframework: TRACE

# spring:
#   application:
#     name: DEV - Loan Dispersal System      



# #Spring MySQL configuration
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/loanapp
#     username: root
#     password: Deep@1007  
#     driver-class-name: com.mysql.cj.jdbc.Driver

# #JPA configuration
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect  

